from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

urlpatterns = [
    path('', inicio, name="inicio"),
    path('lista-actores/', ListarActores.as_view(), name="lista_actores"),
    path('lista-directores/', ListarDirectores.as_view(), name="lista_directores"),
    path('lista-pelis/', ListarPelis.as_view(), name="lista_pelis"),
    path('lista-criticos/', ListarCriticos.as_view(), name="lista_criticos"),
    path('pages/', ListarCriticas.as_view(), name="lista_criticas"),
    path('lista-criticas/<int:pk>/', ListarCriticasID.as_view(), name='lista_criticas_id'),
    path('detalle-actor/<int:pk>/', DetalleActor.as_view(), name="detalleActor"),
    path('detalle-director/<int:pk>/', DetalleDirector.as_view(), name="detalleDirector"),
    path('detalle-peli/<int:pk>/', DetallePelicula.as_view(), name="detallePeli"),
    path('detalle-critico/<int:pk>/', DetalleCritico.as_view(), name="detalleCritico"),
    path('pages/<int:pk>/', DetalleCritica.as_view(), name="detalleCritica"),
    path('crear-actor/', CrearActor.as_view(), name="crearActor"),
    path('crear-director/', CrearDirector.as_view(), name="directorFormulario"),
    path('crear-peli/', CrearPelicula.as_view(), name="peliFormulario"),
    path('crear-critico/', CrearCritico.as_view(), name="crearCritico"),
    path('crear-critica/<int:pk>/', CrearCritica.as_view(), name="crearCritica"),
    path('editar-actor/<int:pk>/', ActualizarActor.as_view(), name="actualizarActor"),
    path('editar-director/<int:pk>/', ActualizarDirector.as_view(), name="actualizarDirector"),
    path('editar-peli/<int:pk>/', ActualizarPelicula.as_view(), name="actualizarPelicula"),
    path('editar-critico/<int:pk>/', ActualizarCritico.as_view(), name="actualizarCritico"),
    path('editar-critica/<int:pk>/', ActualizarCritica.as_view(), name="actualizarCritica"),
    path('eliminar-actor/<int:pk>/', BorrarActor.as_view(), name="eliminarActor"),
    path('eliminar-director/<int:pk>/', BorrarDirector.as_view(), name="eliminarDirector"),
    path('eliminar-peli/<int:pk>/', BorrarPelicula.as_view(), name="eliminarPelicula"),
    path('eliminar-critico/<int:pk>/', BorrarCritico.as_view(), name="eliminarCritico"),
    path('eliminar-critica/<int:pk>/', BorrarCritica.as_view(), name="eliminarCritica"),
    path('busqueda-actor/', busquedaActor, name="busquedaActor"),
    path('busqueda-director/', busquedaDirector, name="busquedaDirector"),
    path('busqueda-pelicula/', busquedaPelicula, name="busquedaPelicula"),
    path('buscar/', buscar, name="buscar"),
    path('login/', loginView, name="login"),
    path('register/', register, name="registro"),
    path('logout/', LogoutView.as_view(template_name="logout.html"), name="logout"),
    path('editar-perfil/', editar_perfil, name="editarPerfil"),
    path('about/', about, name="about"),
]