from django.urls import path
from .views import *

urlpatterns = [
    path('', inicio, name="inicio"),
    #path('agrega-film/<título>/<año>/<director>/<productora>', película),
    #path('agrega-actor/<nombre>/<apellido>/', actor),
    #path('agrega-director/<nombre>/<apellido>/', director),
    #path('agrega-productora/<nombre>/', productora),
    path('lista-actores/', ListarActores.as_view(), name="lista_actores"),
    path('lista-directores/', ListarDirectores.as_view(), name="lista_directores"),
    path('lista-pelis/', ListarPelis.as_view(), name="lista_pelis"),
    path('lista-criticos/', ListarCriticos.as_view(), name="lista_criticos"),
    path('lista-criticas/', ListarCriticas.as_view(), name="lista_criticas"),
    path('detalle-actor/<pk>', DetalleActor.as_view(), name="detalleActor"),
    path('detalle-director/<pk>', DetalleDirector.as_view(), name="detalleDirector"),
    path('detalle-peli/<pk>', DetallePelicula.as_view(), name="detallePeli"),
    path('detalle-critico/<pk>', DetalleCritico.as_view(), name="detalleCritico"),
    path('detalle-critica/<pk>', DetalleCritica.as_view(), name="detalleCritica"),
    path('crear-actor/', CrearActor.as_view(), name="crearActor"),
    path('crear-director/', CrearDirector.as_view(), name="directorFormulario"),
    path('crear-peli/', CrearPelicula.as_view(), name="peliFormulario"),
    path('crear-critico/', CrearCritico.as_view(), name="crearCritico"),
    path('crear-critica/', CrearCritica.as_view(), name="crearCritica"),
    path('editar-actor/<pk>', ActualizarActor.as_view(), name="actualizarActor"),
    path('editar-director/<pk>', ActualizarDirector.as_view(), name="actualizarDirector"),
    path('editar-peli/<pk>', ActualizarPelicula.as_view(), name="actualizarPelicula"),
    path('editar-critico/<pk>', ActualizarCritico.as_view(), name="actualizarCritico"),
    path('editar-critica/<pk>', ActualizarCritica.as_view(), name="actualizarCritica"),
    path('eliminar-actor/<pk>', BorrarActor.as_view(), name="eliminarActor"),
    path('eliminar-director/<pk>', BorrarDirector.as_view(), name="eliminarDirector"),
    path('eliminar-peli/<pk>', BorrarPelicula.as_view(), name="eliminarPelicula"),
    path('eliminar-critico/<pk>', BorrarCritico.as_view(), name="eliminarCritico"),
    path('eliminar-critica/<pk>', BorrarCritica.as_view(), name="eliminarCritica"),
    path('busqueda-actor/', busquedaActor, name="busquedaActor"),
    path('busqueda-director/', busquedaDirector, name="busquedaDirector"),
    path('busqueda-pelicula/', busquedaPelicula, name="busquedaPelicula"),
    path('buscar/', buscar, name="buscar"),
]