# Generated by Django 4.2.5 on 2023-09-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('fundacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Película',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('director', models.CharField(max_length=10)),
                ('productora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.productora')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('nacimiento', models.DateField()),
                ('películas', models.ManyToManyField(to='AppProyecto.película')),
            ],
        ),
    ]
