# Generated by Django 4.2.5 on 2023-09-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='película',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.director'),
        ),
    ]
