# Generated by Django 4.2.5 on 2023-09-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0004_remove_actor_nacimiento_remove_director_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productora',
            name='películas',
        ),
        migrations.AddField(
            model_name='película',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.director'),
        ),
        migrations.AddField(
            model_name='película',
            name='productora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.productora'),
        ),
        migrations.AlterField(
            model_name='director',
            name='apellido',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='director',
            name='nombre',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
