# Generated by Django 4.2.5 on 2023-09-10 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0005_remove_productora_películas_película_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='película',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.director'),
        ),
        migrations.AlterField(
            model_name='película',
            name='productora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.productora'),
        ),
    ]
