# Generated by Django 4.2.5 on 2023-09-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0006_alter_película_director_alter_película_productora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='película',
            old_name='nombre',
            new_name='título',
        ),
        migrations.AlterUniqueTogether(
            name='película',
            unique_together={('título', 'director')},
        ),
    ]
