# Generated by Django 4.2.5 on 2023-10-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0007_rename_nombre_película_título_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Critico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Unknown', max_length=10)),
                ('apellido', models.CharField(default='Unknown', max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='película',
            name='año',
        ),
        migrations.RemoveField(
            model_name='película',
            name='productora',
        ),
        migrations.AlterField(
            model_name='película',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.director'),
        ),
        migrations.DeleteModel(
            name='Productora',
        ),
        migrations.AddField(
            model_name='critica',
            name='critico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.critico'),
        ),
        migrations.AddField(
            model_name='critica',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.película'),
        ),
    ]
