# Generated by Django 4.2.5 on 2023-10-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0008_critica_critico_usuario_remove_película_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='película',
            name='productora',
            field=models.CharField(default='Desconocida', max_length=30),
        ),
        migrations.AlterField(
            model_name='critico',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=10),
        ),
        migrations.AlterField(
            model_name='critico',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=10),
        ),
        migrations.AlterField(
            model_name='director',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=10),
        ),
        migrations.AlterField(
            model_name='director',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=10),
        ),
    ]
