# Generated by Django 4.2.5 on 2023-10-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0011_alter_critico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critico',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='critico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='critico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='critico',
            name='user',
        ),
    ]
