# Generated by Django 4.2.5 on 2023-10-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0013_critico_apellido_critico_email_critico_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critico',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='critico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='critico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='critico',
            name='user',
        ),
    ]
