# Generated by Django 4.2.5 on 2023-10-05 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppProyecto', '0014_remove_critico_apellido_remove_critico_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='critico',
            name='apellido',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='critico',
            name='email',
            field=models.EmailField(default='Unknown@unknown.com', max_length=254),
        ),
        migrations.AddField(
            model_name='critico',
            name='nombre',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='critico',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
