# Generated by Django 4.2.5 on 2023-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0015_critico_apellido_critico_email_critico_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
