# Generated by Django 4.2.5 on 2023-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0016_alter_critico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
