# Generated by Django 4.2.5 on 2023-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0017_alter_critico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='apellido',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='critico',
            name='apellido',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='director',
            name='apellido',
            field=models.CharField(default='Unknown', max_length=25),
        ),
    ]
