# Generated by Django 4.2.5 on 2023-10-05 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0018_alter_actor_apellido_alter_critico_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='critica',
            name='imagen',
            field=models.ImageField(default='image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='critica',
            name='subtitulo',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
